version: '3'
services:
  web:
    environment:
      EMAIL: nagisa.s.0716@gmail.com
      PASSWORD: 'bdlwwhvwendwohmy'
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    links:
      - db

  nginx:
    build: nginx
    volumes:
      - public-data:/app_name/public
      - tmp-data:/app_name/tmp
    ports:
      - "80:80"
    depends_on:
      - web


  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"


volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: